{{ config(materialized='table') }}

SELECT 
  {{ orbit_category('ECCENTRICITY', 'PERIOD', 'INCLINATION', 'SEMIMAJOR_AXIS') }} AS ORBIT_CAT,
  COUNT(*) AS SAT_COUNT,
  AVG(DATE_DIFF(
    COALESCE(DECAY_DATE, CURRENT_DATE), 
    LAUNCH_DATE, 
    DAY
  )) AS AVG_ORBIT_DAYS,
  MIN(DATE_DIFF(
    COALESCE(DECAY_DATE, CURRENT_DATE), 
    LAUNCH_DATE, 
    DAY
  )) AS MIN_ORBIT_DAYS,
  MAX(DATE_DIFF(
    COALESCE(DECAY_DATE, CURRENT_DATE), 
    LAUNCH_DATE, 
    DAY
  )) AS MAX_ORBIT_DAYS,
  AVG(CASE WHEN BSTAR BETWEEN 0 AND 0.1 THEN BSTAR ELSE NULL END) AS AVG_DRAG
FROM {{ source('project_zoomcamp', 'spacetrack_gp_data') }}
WHERE 
  OBJECT_TYPE = 'PAYLOAD' 
  AND LAUNCH_DATE IS NOT NULL
  AND (DECAY_DATE IS NULL OR DATE_DIFF(DECAY_DATE, LAUNCH_DATE, DAY) >= 0)
GROUP BY ORBIT_CAT
ORDER BY AVG_DRAG DESC NULLS LAST