version: 2

sources:
  - name: project_zoomcamp
    database: # Here you will insert your project-id
    schema: project_zoomcamp
    tables:
      - name: spacetrack_gp_data
        description: "space track general perturbations data containing satellite and debris information"

  - name: dbt_satellite_analytics
    database: # Insert your project id here as well
    schema: dbt_satellite_analytics
    tables:
      - name: launches_stats
        description: "derived data containing stats about launches"
      - name: orbit_debris
        description: "derived data containing orbit info about debris in orbit"
      
      - name: lifespan_orbit
        description: "derived information about satellite lifespan per orbit category"
