{{ config(materialized='table') }}

WITH ORBIT_DEBRIS AS (
    SELECT 
        o.OBJECT_TYPE,
        o.NORAD_CAT_ID,
        o.COUNTRY_CODE,
        o.SEMIMAJOR_AXIS,
        o.PERIOD,
        o.INCLINATION,
        o.LAUNCH_DATE,
        {{ orbit_category('ECCENTRICITY', 'PERIOD', 'INCLINATION', 'SEMIMAJOR_AXIS') }} AS ORBIT_CAT
        FROM {{ source('project_zoomcamp', 'spacetrack_gp_data') }} AS o
        WHERE (o.OBJECT_TYPE = 'DEBRIS' OR o.OBJECT_TYPE = 'ROCKET BODY') 
        AND o.DECAY_DATE IS NULL
),

ORBIT_CATEGORY_COUNTS AS (
    SELECT
        COUNTRY_CODE,
        COUNTIF(ORBIT_CAT = 'LEO') AS LEO_COUNT,
        COUNTIF(ORBIT_CAT = 'PO') AS PO_COUNT,
        COUNTIF(ORBIT_CAT = 'GEO') AS GEO_COUNT,
        COUNTIF(ORBIT_CAT = 'GSO') AS GSO_COUNT,
        COUNTIF(ORBIT_CAT = 'MEO') AS MEO_COUNT,
        COUNTIF(ORBIT_CAT = 'OTHER') AS OTHER_ORBIT_COUNT
    FROM ORBIT_DEBRIS
    WHERE COUNTRY_CODE IS NOT NULL
    GROUP BY COUNTRY_CODE
),

COUNTRY_DEBRIS AS (
    SELECT 
        COUNTRY_CODE,
        COUNT(*) AS ACTIVE_OBJECTS_COUNT,
        AVG(SEMIMAJOR_AXIS) AS AVG_SEMIMAJOR_AXIS,
        AVG(PERIOD) AS AVG_PERIOD,
        AVG(INCLINATION) AS AVG_INCLINATION,
        AVG(DATE_DIFF(CURRENT_DATE(), LAUNCH_DATE, DAY)) AS AVG_ORBIT_DAYS,
        COUNTIF(OBJECT_TYPE = 'DEBRIS') AS DEBRIS_COUNT,
        COUNTIF(OBJECT_TYPE = 'ROCKET BODY') AS ROCKET_BODY_COUNT
    FROM ORBIT_DEBRIS
    WHERE COUNTRY_CODE IS NOT NULL
    GROUP BY COUNTRY_CODE
)

SELECT
    cd.*,
    oc.LEO_COUNT,
    oc.PO_COUNT,
    oc.GEO_COUNT,
    oc.GSO_COUNT,
    oc.MEO_COUNT,
    oc.OTHER_ORBIT_COUNT
FROM COUNTRY_DEBRIS cd
JOIN ORBIT_CATEGORY_COUNTS oc
    ON cd.COUNTRY_CODE = oc.COUNTRY_CODE
ORDER BY cd.COUNTRY_CODE ASC